Repository cp-geeks-adgitm/CompetitiveProgramming, pull requests merged in 2022-10, with the labels that each got.

#9 anuj [TrappingRainWater.java]
  TrappingRainWater.java
Labels: hacktoberfest-accepted

#14 added binary search iterative version
  Searching Algorithms/Binary_Search_Iteratively.cpp
Labels: hacktoberfest-accepted

#19 Added add two number question
  Linked List/add_two_numbers-Leetcode.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#21 reverse integer question leetcode
  Miscellaneous/reverse_integer-Leetcode.cpp
Labels: hacktoberfest

#22 leetcode question most water
  Array/contain_with_most_water-Leetcode.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#23 merge k sorted list question
  Linked List/merge_k_sorted_lists-leetcode.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#24 Added Leetcode Trapping Rain Water
  Array/Trapping Rain Water.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#25 Added LeetCode Set Matrix Zeroes
  Array/Set Matrix Zeroes.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#26 Added LeetCode Spiral Matrix II
  Array/Spiral Matrix II.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#27 Add LeetCode Subsets II
  Subsets II.cpp
Labels: hacktoberfest-accepted, hacktoberfest
